module.exports = {
  ROLES: { ADMIN: "ADMIN", MANAGER: "MANAGER", CASHIER: "CASHIER" },
  ALLOWED_LOGIN_ROLES: ["ADMIN", "MANAGER", "CASHIER"],
  ORDER_STATUS: ["CREATED", "CONFIRMED", "PARTIALLY_PAID", "PAID", "READY_FOR_DELIVERY", "DELIVERED", "CANCELLED", "RETURNED", "REFUNDED"],
  PAYMENT_STATUS: ["PENDING", "SUCCESS", "FAILED", "REFUNDED"],
  STOCK_STATUS: ["IN_STOCK", "LOW_STOCK", "OUT_OF_STOCK"]
};
